spring:
  application:
    name: api-gateway
# api gateway's file should be kept in its own resources
#    config:
#      import: optional:configserver:http://localhost:8888
#    cloud:
#      gateway:
#        routes:
#          - id: user-service
#            uri: lb://user-service
#            predicates:
#              - Path=/users/**
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
           - id: user-service
             uri: lb://user-service
             predicates:
                - Path=/users/**
           - id: order-service
             uri: lb://order-service
             predicates:
                - Path=/orders/**
           - id: inventory-service
             uri: lb://inventory-service
             predicates:
                - Path=/inventory/**

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: learning-microservices-api-gateway
            client-secret: Z46gdfg54TGKjCdsgfg445446gsdfg9dgsfgkOsoM8IHAr0X1xwVs46542dfgsgjlbpiIeuR3
            provider: keycloak
            authorization-grant-type: authorization_code
#            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - openid
        provider:
          keycloak:
            issuer-uri: http://localhost:8555/realms/learn-microservices-realm
      resource-server:
        jwt:
          issuer-uri: http://localhost:8555/realms/learn-microservices-realm





#We dont usually need this, adding the client dependency is usually enough, but just to be save, we have added this
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8765

#for logging of req mapping
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
    org.springframework.security: DEBUG

  pattern:
    level:%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}] #SB3

#spring zipkin
management:
  tracing:
    sampling:
      probability: 1.0 # specifies the percentage of reqs we'd want to trace, as we are using it for learning purposes currently, I have set it up to 100%
    zipkin:
      enabled: true
#logging:

#initial config, might change