  #// Routes all requests starting with /users to user-service.
  spring:
#    config:
#      import: optional:configserver:http://localhost:8888
    cloud:
      gateway:
        routes:
          - id: user-service
            uri: lb://user-service
            predicates:
              - Path=/users/**

#initial config, might change