  #// Routes all requests starting with /users to user-service.
spring:
#    config:
#      import: optional:configserver:http://localhost:8888
    cloud:
      gateway:
        routes:
          - id: user-service
            uri: lb://user-service
            predicates:
              - Path=/users/**


#We dont usually need this, adding the client dependency is usually enough, but just to be save, we have added this
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka



#initial config, might change