spring:
  application:
    name: inventory-service
#  cloud:
  config:
      import: optional:configserver:http://localhost:8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
#initial config, might change