spring:
  application:
    name: inventory-service
#  cloud:
  config:
      import: optional:configserver:http://localhost:8888


#We dont usually need this, adding the client dependency is usually enough, but just to be save, we have added this
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka



#spring zipkin
management:
  tracing:
    sampling:
      probability: 1.0 # specifies the percentage of reqs we'd want to trace, as we are using it for learning purposes currently, I have set it up to 100%
    zipkin:
      enabled: true