 # // Port 8888 is the default for Config Servers.
spring:
    application:
      name: config-server
    cloud:
      config:
        server:
          git:
#            uri: file:///home/sufiyan/Desktop/IdeaProjects/properties-repo-for-learn-microservices #for linux
            uri: C:\Users\Sufiyan\Desktop\Code\BE\properties-repo-for-learn-microservices #for windows

server:
    port: 8888

 #We dont usually need this, adding the client dependency is usually enough, but just to be save, we have added this
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka



#  git:
#    uri: file://home/sufiyan/Desktop/IdeaProjects/properties-repo-for-learn-microservices

#    uri: file:///path/to/your/local/git-repo
    # Configuration files are stored in a Git repository for version control.
    # Replace with your actual path.

    # For remote Git repositories, uncomment and replace with your repo URL.
    # uri: https://github.com/your-org/config-repo.git
    # username: your-username
    # password: your-password
    # This allows the Config Server to access private Git repositories.
    #or you can use access token as well


 #spring zipkin
management:
  tracing:
    sampling:
      probability: 1.0 # specifies the percentage of reqs we'd want to trace, as we are using it for learning purposes currently, I have set it up to 100%
    zipkin:
      enabled: true